name: Strapi Develop to Main - CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i" # --delete  
        SOURCE: "/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/home/rafael/teste"
        EXCLUDE: "/.cache/, .editorconfig, .env.example, .eslintignore, .eslintrc, /.git/, /.github/, .gitignore, .strapi-updater.json, README.md, /build/, /config/, /database/, favicon.png, local_ssh_script-before.sh, /node_modules/, package.json, package-lock.json, /public/, strapiloader.js, yarn.lock"
        SCRIPT_BEFORE: |
          echo "SCRIPT_BEFORE"
          echo "whoami"
          whoami
          echo "ls -la"
          ls -al
          echo "🚀🚀🚀 STOP PM2 🚀🚀🚀"
          echo "pm2 kill"
          pm2 kill
          echo "pm2 status"
          pm2 status"
        SCRIPT_AFTER: |
          echo "SCRIPT_AFTER"
          echo "whoami"
          whoami
          echo "ls -la"
          ls -al
          echo "🚀🚀🚀 Runnin PM2 - Strapi to the moon 🚀🚀🚀"
          echo "NODE_ENV=production pm2 start /home/rafael/strapi-server/strapiloader.js -i max --env production"
          NODE_ENV=production pm2 start /home/rafael/strapi-server/strapiloader.js -i max --env production
          echo "pm2 status"
          pm2 status"
          echo $RSYNC_STDOUT