name: Strapi Develop to Main - CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i" # --delete  
        SOURCE: "/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/home/rafael/teste"
        SCRIPT_BEFORE: |
          echo "SCRIPT_BEFORE"
          echo "whoami"
          whoami
          echo "ls -la"
          ls -al
        SCRIPT_AFTER: |
          echo "SCRIPT_AFTER"
          echo "whoami"
          whoami
          echo "ls -la"
          ls -al
          echo $RSYNC_STDOUT